### ISSUE TITLE
Paths when running training

### ISSUE THREAD

**Issue by bbieniek** [nedap/deidentify#57]
Hi,

While running training via run_bilstmcrf.py I ran it the following way:
Installed deidentify via pip
Checked out the code from github to have run_bilstmcrf.py

When running the run_bilstmcrf.py script, this resulted in issues with the paths for the training set as the scripts use base path in most cases.

Is this the correct way of running the training?

**Comment by jantrienes** [comment]
Hi @bbieniek, 

thanks for reaching out. The recommended way to train a model with the `run_bilstmcrf.py` script is to 1) clone the repo, 2) create the virtual environment (see [here](https://github.com/nedap/deidentify#computational-environment)), and 3) train the model according to [these steps](https://github.com/nedap/deidentify/blob/master/docs/02_train_evaluate_models.md). No pip install is needed in this case, because you are working from the sources itself. 

> When running the run_bilstmcrf.py script, this resulted in issues with the paths for the training set as the scripts use base path in most cases.

All scripts assume that the training data resides in `data/corpus/`. Could you perhaps share the specific error you received? That would make it easier to analyze the problem. Thank you.

Best,
Jan

**Comment by jantrienes** [comment]
I'm closing this for now. Please let me know if you have additional questions.

**Comment by bbieniek** [comment]
Thanks Jan for your response. That helped!
